name: Alerta Discord

on:
  push:
    branches: [ "main" ]

jobs:
  notificacao:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "🚀 Um novo commit acabou de ser feito no branch main do nosso projeto DevOps!"}' \
          ${{ secrets.DISCORD_WEBHOOK }}